DROP TABLE IF EXISTS COMPANY;
CREATE TABLE COMPANY(
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	NAME VARCHAR(255), 
	ADDRESS VARCHAR(255), 
	CREATED_BY VARCHAR(255), 
	CREATED_AT DATETIME, 
	UPDATED_BY VARCHAR(255), 
	UPDATED_AT DATETIME
);

DROP TABLE IF EXISTS CLIENT;
CREATE TABLE CLIENT(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	COMPANY_ID INT, NAME VARCHAR(255), 
	NAME VARCHAR(255), 
	EMAIL VARCHAR(255), 
	PHONE VARCHAR(255), 
	CREATED_BY VARCHAR(255), 
	CREATED_AT DATETIME, 
	UPDATED_BY VARCHAR(255), 
	UPDATED_AT DATETIME
);